# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mainflux' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'Firebase/Core', '5.20.1'
  pod 'Firebase/Firestore', '5.20.1'
  pod 'Firebase/Auth', '5.20.1'




  pod 'FBSDKCoreKit', '~> 5.0.1'
  pod 'FBSDKLoginKit', '~> 5.0.1'
  pod 'FBSDKShareKit', '~> 5.0.1'
  
  

#  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

#  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNFirebase', path: '../node_modules/react-native-firebase/ios'
  pod 'GoogleSignIn', '4.4.0'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  
 # pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  
 # pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end
